#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P03AplikacjaZawodnicy.Core.Repositories
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="A_Zawodnicy")]
	public partial class ModelBazyDanychDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTrener(Trener instance);
    partial void UpdateTrener(Trener instance);
    partial void DeleteTrener(Trener instance);
    partial void InsertZawodnik(Zawodnik instance);
    partial void UpdateZawodnik(Zawodnik instance);
    partial void DeleteZawodnik(Zawodnik instance);
    partial void InsertSkocznia(Skocznia instance);
    partial void UpdateSkocznia(Skocznia instance);
    partial void DeleteSkocznia(Skocznia instance);
    partial void InsertMiasto(Miasto instance);
    partial void UpdateMiasto(Miasto instance);
    partial void DeleteMiasto(Miasto instance);
    #endregion
		
		public ModelBazyDanychDataContext() : 
				base(global::P03AplikacjaZawodnicy.Core.Properties.Settings.Default.A_ZawodnicyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelBazyDanychDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelBazyDanychDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelBazyDanychDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelBazyDanychDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Trener> Trener
		{
			get
			{
				return this.GetTable<Trener>();
			}
		}
		
		public System.Data.Linq.Table<Zawodnik> Zawodnik
		{
			get
			{
				return this.GetTable<Zawodnik>();
			}
		}
		
		public System.Data.Linq.Table<Skocznia> Skocznia
		{
			get
			{
				return this.GetTable<Skocznia>();
			}
		}
		
		public System.Data.Linq.Table<Miasto> Miasto
		{
			get
			{
				return this.GetTable<Miasto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.trenerzy")]
	public partial class Trener : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private System.Nullable<System.DateTime> _DataUr;
		
		private EntitySet<Zawodnik> _Zawodnik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnDataUrChanging(System.Nullable<System.DateTime> value);
    partial void OnDataUrChanged();
    #endregion
		
		public Trener()
		{
			this._Zawodnik = new EntitySet<Zawodnik>(new Action<Zawodnik>(this.attach_Zawodnik), new Action<Zawodnik>(this.detach_Zawodnik));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_trenera", Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="imie_t", Storage="_Imie", DbType="VarChar(255)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nazwisko_t", Storage="_Nazwisko", DbType="VarChar(255)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_ur_t", Storage="_DataUr", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataUr
		{
			get
			{
				return this._DataUr;
			}
			set
			{
				if ((this._DataUr != value))
				{
					this.OnDataUrChanging(value);
					this.SendPropertyChanging();
					this._DataUr = value;
					this.SendPropertyChanged("DataUr");
					this.OnDataUrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trener_Zawodnik", Storage="_Zawodnik", ThisKey="Id", OtherKey="IdTrenera")]
		public EntitySet<Zawodnik> Zawodnik
		{
			get
			{
				return this._Zawodnik;
			}
			set
			{
				this._Zawodnik.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Zawodnik(Zawodnik entity)
		{
			this.SendPropertyChanging();
			entity.Trener = this;
		}
		
		private void detach_Zawodnik(Zawodnik entity)
		{
			this.SendPropertyChanging();
			entity.Trener = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zawodnicy")]
	public partial class Zawodnik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdTrenera;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private string _Kraj;
		
		private System.Nullable<System.DateTime> _DataUr;
		
		private System.Nullable<int> _Wzrost;
		
		private System.Nullable<int> _Waga;
		
		private EntityRef<Trener> _Trener;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdTreneraChanging(System.Nullable<int> value);
    partial void OnIdTreneraChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnKrajChanging(string value);
    partial void OnKrajChanged();
    partial void OnDataUrChanging(System.Nullable<System.DateTime> value);
    partial void OnDataUrChanged();
    partial void OnWzrostChanging(System.Nullable<int> value);
    partial void OnWzrostChanged();
    partial void OnWagaChanging(System.Nullable<int> value);
    partial void OnWagaChanged();
    #endregion
		
		public Zawodnik()
		{
			this._Trener = default(EntityRef<Trener>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_zawodnika", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_trenera", Storage="_IdTrenera", DbType="Int")]
		public System.Nullable<int> IdTrenera
		{
			get
			{
				return this._IdTrenera;
			}
			set
			{
				if ((this._IdTrenera != value))
				{
					this.OnIdTreneraChanging(value);
					this.SendPropertyChanging();
					this._IdTrenera = value;
					this.SendPropertyChanged("IdTrenera");
					this.OnIdTreneraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="imie", Storage="_Imie", DbType="VarChar(255)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nazwisko", Storage="_Nazwisko", DbType="VarChar(255)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kraj", Storage="_Kraj", DbType="VarChar(255)")]
		public string Kraj
		{
			get
			{
				return this._Kraj;
			}
			set
			{
				if ((this._Kraj != value))
				{
					this.OnKrajChanging(value);
					this.SendPropertyChanging();
					this._Kraj = value;
					this.SendPropertyChanged("Kraj");
					this.OnKrajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_ur", Storage="_DataUr", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataUr
		{
			get
			{
				return this._DataUr;
			}
			set
			{
				if ((this._DataUr != value))
				{
					this.OnDataUrChanging(value);
					this.SendPropertyChanging();
					this._DataUr = value;
					this.SendPropertyChanged("DataUr");
					this.OnDataUrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="wzrost", Storage="_Wzrost", DbType="Int")]
		public System.Nullable<int> Wzrost
		{
			get
			{
				return this._Wzrost;
			}
			set
			{
				if ((this._Wzrost != value))
				{
					this.OnWzrostChanging(value);
					this.SendPropertyChanging();
					this._Wzrost = value;
					this.SendPropertyChanged("Wzrost");
					this.OnWzrostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="waga", Storage="_Waga", DbType="Int")]
		public System.Nullable<int> Waga
		{
			get
			{
				return this._Waga;
			}
			set
			{
				if ((this._Waga != value))
				{
					this.OnWagaChanging(value);
					this.SendPropertyChanging();
					this._Waga = value;
					this.SendPropertyChanged("Waga");
					this.OnWagaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trener_Zawodnik", Storage="_Trener", ThisKey="IdTrenera", OtherKey="Id", IsForeignKey=true)]
		public Trener Trener
		{
			get
			{
				return this._Trener.Entity;
			}
			set
			{
				Trener previousValue = this._Trener.Entity;
				if (((previousValue != value) 
							|| (this._Trener.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Trener.Entity = null;
						previousValue.Zawodnik.Remove(this);
					}
					this._Trener.Entity = value;
					if ((value != null))
					{
						value.Zawodnik.Add(this);
						this._IdTrenera = value.Id;
					}
					else
					{
						this._IdTrenera = default(Nullable<int>);
					}
					this.SendPropertyChanged("Trener");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.skocznie")]
	public partial class Skocznia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdMiasta;
		
		private string _Nazwa;
		
		private System.Nullable<int> _K;
		
		private System.Nullable<int> _Sedz;
		
		private string _Kraj;
		
		private EntityRef<Miasto> _Miasto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdMiastaChanging(System.Nullable<int> value);
    partial void OnIdMiastaChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnKChanging(System.Nullable<int> value);
    partial void OnKChanged();
    partial void OnSedzChanging(System.Nullable<int> value);
    partial void OnSedzChanged();
    partial void OnKrajChanging(string value);
    partial void OnKrajChanged();
    #endregion
		
		public Skocznia()
		{
			this._Miasto = default(EntityRef<Miasto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_skoczni", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_miasta", Storage="_IdMiasta", DbType="Int")]
		public System.Nullable<int> IdMiasta
		{
			get
			{
				return this._IdMiasta;
			}
			set
			{
				if ((this._IdMiasta != value))
				{
					this.OnIdMiastaChanging(value);
					this.SendPropertyChanging();
					this._IdMiasta = value;
					this.SendPropertyChanged("IdMiasta");
					this.OnIdMiastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nazwa_skoczni", Storage="_Nazwa", DbType="VarChar(50)")]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="k", Storage="_K", DbType="Int")]
		public System.Nullable<int> K
		{
			get
			{
				return this._K;
			}
			set
			{
				if ((this._K != value))
				{
					this.OnKChanging(value);
					this.SendPropertyChanging();
					this._K = value;
					this.SendPropertyChanged("K");
					this.OnKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sedz", Storage="_Sedz", DbType="Int")]
		public System.Nullable<int> Sedz
		{
			get
			{
				return this._Sedz;
			}
			set
			{
				if ((this._Sedz != value))
				{
					this.OnSedzChanging(value);
					this.SendPropertyChanging();
					this._Sedz = value;
					this.SendPropertyChanged("Sedz");
					this.OnSedzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kraj_skoczni", Storage="_Kraj", DbType="VarChar(255)")]
		public string Kraj
		{
			get
			{
				return this._Kraj;
			}
			set
			{
				if ((this._Kraj != value))
				{
					this.OnKrajChanging(value);
					this.SendPropertyChanging();
					this._Kraj = value;
					this.SendPropertyChanged("Kraj");
					this.OnKrajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="miasta_skocznie", Storage="_Miasto", ThisKey="IdMiasta", OtherKey="Id", IsForeignKey=true)]
		public Miasto Miasto
		{
			get
			{
				return this._Miasto.Entity;
			}
			set
			{
				Miasto previousValue = this._Miasto.Entity;
				if (((previousValue != value) 
							|| (this._Miasto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Miasto.Entity = null;
						previousValue.Skocznia.Remove(this);
					}
					this._Miasto.Entity = value;
					if ((value != null))
					{
						value.Skocznia.Add(this);
						this._IdMiasta = value.Id;
					}
					else
					{
						this._IdMiasta = default(Nullable<int>);
					}
					this.SendPropertyChanged("Miasto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.miasta")]
	public partial class Miasto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nazwa;
		
		private EntitySet<Skocznia> _Skocznia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    #endregion
		
		public Miasto()
		{
			this._Skocznia = new EntitySet<Skocznia>(new Action<Skocznia>(this.attach_Skocznia), new Action<Skocznia>(this.detach_Skocznia));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_miasta", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nazwa_miasta", Storage="_Nazwa", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="miasta_skocznie", Storage="_Skocznia", ThisKey="Id", OtherKey="IdMiasta")]
		public EntitySet<Skocznia> Skocznia
		{
			get
			{
				return this._Skocznia;
			}
			set
			{
				this._Skocznia.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Skocznia(Skocznia entity)
		{
			this.SendPropertyChanging();
			entity.Miasto = this;
		}
		
		private void detach_Skocznia(Skocznia entity)
		{
			this.SendPropertyChanging();
			entity.Miasto = null;
		}
	}
}
#pragma warning restore 1591
